dist: xenial

sudo:
  required

services:
  - docker

language: java
jdk: openjdk11

script: mvn clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - eaxdev@ya.ru